apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: corp-services
  namespace: market-making
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: corp.local
      http:
        paths:
          - path: /trading(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: trading-engine
                port:
                  number: 8080
          - path: /risk(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: risk-monitor
                port:
                  number: 8081
          - path: /market-data(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: market-data-collector
                port:
                  number: 8082
