apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: market-making
resources:
  - namespace.yaml
  - mm-secrets.template.yaml
  - trading-engine.yaml
  - risk-monitor.yaml
  - market-data-collector.yaml
  - ingress.yaml
